baseURL = 'https://ftith.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'PaperMod'
paginate = 5

[params]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowToc = true

