baseURL = 'https://ftith.github.io/'
languageCode = 'en-us'
title = 'f.t'
theme = 'PaperMod'
paginate = 5

[params]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowToc = true
githubUrl = "https://github.com/ftith/ftith.github.io"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog. I am a DevOps Engineer working for a video game company."

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20
[outputs]
home = [ "HTML", "RSS", "JSON" ]
